# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


email: hello@fastfamiliar.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: fastfamiliar
facebook_username: fastfamiliar
instagram_username: fastfamiliarstudio

# SEO information
title: Fast Familiar
tagline: participatory, playful + political artworks
description: >- # this means to ignore newlines until "baseurl:"
  Fast Familiar design audience-centric experiences which use digital technology to enable new forms of human connection. FF's lead artists are Dan Barnard, Joe McAlister and Rachel Briscoe.
url: "https://fastfamiliar.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: fastfamiliar
  card: summary
logo: https://cdn.fastfamiliar.com/img/fastfamiliar/vector-dynamic.svg
social:
  name: Fast Familiar
  links:
    - https://twitter.com/fastfamiliar
    - https://facebook.com/fastfamiliar
    - https://instagram.com/fastfamiliarstudio
locale: en_UK
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/seo/default-image.png

# Build settings
plugins:
  - jekyll-feed
  - jekyll-youtube
  - jekyll_version_plugin
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-redirect-from

# minifier
jekyll-minifier:
  exclude: 'rss-feed.js'
  uglifier_args:
    harmony: true

# menubar
menubar-items:
  - Climate action
  - Digital artworks
  - Education + Research Tools
  - FF For fun
  - Consultancy/ facilitation

menubar-links:
  - /climate-action
  - /artwork
  - /education-research
  - /for-fun
  - /facilitation-and-consultancy

menubar-explode-items:
  - About us
  - Process blog
  - Contact us

menubar-explode-links:
  - /about/
  - https://workroom.fastfamiliar.com/
  - /contact-us/



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
